---
# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # if you don't do these things before calling goreleaser, it might be a
    # good idea to do them here:
    - rustup default stable
    - cargo install --locked cargo-zigbuild
    - cargo fetch --locked

builds:
  - builder: rust
    flags:
      - --release
    targets:
      - aarch64-unknown-linux-gnu
      - x86_64-unknown-linux-gnu

# Build container images
dockers:
  - dockerfile: "docker/Dockerfile.goreleaser"
    goarch: "amd64"
    goos: "linux"
    use: "buildx"
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--platform=linux/amd64"
    image_templates:
      - "ghcr.io/phyber/kube-mdns:{{ .Tag }}-amd64"
  - dockerfile: "docker/Dockerfile.goreleaser"
    goarch: "arm64"
    goos: "linux"
    use: "buildx"
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--platform=linux/arm64"
    image_templates:
      - "ghcr.io/phyber/kube-mdns:{{ .Tag }}-arm64"

docker_manifests:
  - name_template: "ghcr.io/phyber/kube-mdns:{{ .Tag }}"
    image_templates:
      - "ghcr.io/phyber/kube-mdns:{{ .Tag }}-amd64"
      - "ghcr.io/phyber/kube-mdns:{{ .Tag }}-arm64"

archives:
  - formats:
      - "tar.gz"
    # this name template makes the OS and Arch compatible with the results of
    # `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

