---
version: 2

before:
  hooks:
    - "rustup default stable"
    - "cargo install --locked cargo-zigbuild"
    - "cargo fetch --locked"

builds:
  - builder: "rust"
    flags:
      - "--release"
    targets:
      - "aarch64-unknown-linux-gnu"
      - "x86_64-unknown-linux-gnu"

# Build container images
dockers:
  - dockerfile: "docker/Dockerfile.goreleaser"
    goarch: "amd64"
    goos: "linux"
    use: "buildx"
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.documentation=https://github.com/phyber/kube-mdns"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.source=https://github.com/phyber/kube-mdns"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.url=https://github.com/phyber/kube-mdns"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--platform=linux/amd64"
    image_templates:
      - "ghcr.io/phyber/kube-mdns:{{ .Tag }}-amd64"
  - dockerfile: "docker/Dockerfile.goreleaser"
    goarch: "arm64"
    goos: "linux"
    use: "buildx"
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.documentation=https://github.com/phyber/kube-mdns"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.source=https://github.com/phyber/kube-mdns"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.url=https://github.com/phyber/kube-mdns"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--platform=linux/arm64"
    image_templates:
      - "ghcr.io/phyber/kube-mdns:{{ .Tag }}-arm64"

docker_manifests:
  - name_template: "ghcr.io/phyber/kube-mdns:{{ .Tag }}"
    image_templates:
      - "ghcr.io/phyber/kube-mdns:{{ .Tag }}-amd64"
      - "ghcr.io/phyber/kube-mdns:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/phyber/kube-mdns:latest"
    image_templates:
      - "ghcr.io/phyber/kube-mdns:{{ .Tag }}-amd64"
      - "ghcr.io/phyber/kube-mdns:{{ .Tag }}-arm64"

archives:
  - formats:
      - "tar.gz"
    # this name template makes the OS and Arch compatible with the results of
    # `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

changelog:
  sort: "asc"
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
