---
{{- if .Values.rbac.create }}
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRole"
metadata:
  name: {{ include "kube-mdns.fullname" . | quote }}
  labels:
    {{- include "kube-mdns.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - "ingresses"
    verbs:
      - "get"
      - "list"
      - "watch"
{{- end }}
