---
{{- if .Values.security.networkPolicy.enabled }}
apiVersion: "networking.k8s.io/v1"
kind: "NetworkPolicy"
metadata:
  name: {{ printf "%s-deny-ingress" (include "kube-mdns.fullname" .) | quote }}
  namespace: {{ include "kube-mdns.namespace" . | quote }}
spec:
  podSelector:
    {{- include "kube-mdns.selectorLabels" . | nindent 4 }}
  policyTypes:
    - "Ingress"
  ingress:
    - to:
      - namespaceSelector:
          matchExpressions:
            - key: "namespace"
              operator: "In"
              values:
                - {{ include "kube-mdns.namespace" . | quote }}
{{- end }}
