---
{{- if .Values.serviceAccount.create }}
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- range $key, $value := .Values.serviceAccount.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  name: {{ include "kube-mdns.serviceAccountName" . | quote }}
  namespace: {{ include "kube-mdns.namespace" . | quote }}
  labels:
    {{- include "kube-mdns.labels" . | nindent 4 }}
    app.kubernetes.io/component: "controller"
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
